
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	rm -rf reports
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ruff_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**
	rm -rf lightning_logs/**

start-tensorboard: ## Start tensorboard
	tensorboard --logdir logs --port 6006

precommit-setup: ## Setup precommit
	pre-commit install

sync: ## Sync dependencies with rye
	rye sync --no-lock

sync-prod: ## Sync dependencies with rye (production)
	rye sync --no-lock --no-dev